modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LatvianModder/Quartz-Chests/issues"

[[mods]]
modId="quartzchests"
version="${file.jarVersion}"
displayName="Quartz Chests"
authors="LatvianModder"
description='''
Adds portable chests with decoration options
'''

[[dependencies.quartzchests]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quartzchests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
